
import com.sun.javafx.image.impl.IntArgb;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class ATM extends javax.swing.JFrame {

    /**
     * Creates new form Finance
     */
    public ATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ABC = new javax.swing.JLabel();
        lb_simple = new javax.swing.JLabel();
        txt_nhap = new javax.swing.JTextField();
        btn_CW = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lb_M5h = new javax.swing.JLabel();
        txt_M500k = new javax.swing.JTextField();
        lb_M200k = new javax.swing.JLabel();
        txt_M200k = new javax.swing.JTextField();
        lb_M100k = new javax.swing.JLabel();
        lb_M50k = new javax.swing.JLabel();
        txt_M100k = new javax.swing.JTextField();
        txt_M50k = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABC Bank");
        setSize(new java.awt.Dimension(200, 200));
        getContentPane().setLayout(null);

        lb_ABC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_ABC.setText("       ABC Bank hân hạnh phục vụ Quý khác");
        getContentPane().add(lb_ABC);
        lb_ABC.setBounds(124, 20, 347, 59);

        lb_simple.setText("Mời nhập số tiền cần rút");
        getContentPane().add(lb_simple);
        lb_simple.setBounds(212, 86, 182, 25);
        getContentPane().add(txt_nhap);
        txt_nhap.setBounds(112, 118, 347, 40);

        btn_CW.setText("Rút tiền");
        btn_CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CWActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CW);
        btn_CW.setBounds(132, 176, 93, 29);

        btn_reset.setText("Làm lại");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(336, 176, 123, 29);

        lb_M5h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/h4.jpg"))); // NOI18N
        getContentPane().add(lb_M5h);
        lb_M5h.setBounds(10, 230, 200, 85);

        txt_M500k.setText("0");
        txt_M500k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_M500kActionPerformed(evt);
            }
        });
        getContentPane().add(txt_M500k);
        txt_M500k.setBounds(217, 273, 56, 40);

        lb_M200k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/s-200k.jpg"))); // NOI18N
        getContentPane().add(lb_M200k);
        lb_M200k.setBounds(10, 370, 200, 79);

        txt_M200k.setText("0");
        txt_M200k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_M200kActionPerformed(evt);
            }
        });
        getContentPane().add(txt_M200k);
        txt_M200k.setBounds(217, 408, 56, 40);
        getContentPane().add(lb_M100k);
        lb_M100k.setBounds(331, 240, 190, 79);
        getContentPane().add(lb_M50k);
        lb_M50k.setBounds(331, 369, 190, 79);

        txt_M100k.setText("0");
        txt_M100k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_M100kActionPerformed(evt);
            }
        });
        getContentPane().add(txt_M100k);
        txt_M100k.setBounds(526, 279, 56, 40);

        txt_M50k.setText("0");
        txt_M50k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_M50kActionPerformed(evt);
            }
        });
        getContentPane().add(txt_M50k);
        txt_M50k.setBounds(526, 408, 56, 40);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_M500kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_M500kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_M500kActionPerformed

    private void txt_M200kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_M200kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_M200kActionPerformed

    private void txt_M100kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_M100kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_M100kActionPerformed

    private void txt_M50kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_M50kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_M50kActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
       
        txt_nhap.setText("");
        txt_M100k.setText("0");
        txt_M200k.setText("0");
        txt_M500k.setText("0");
        txt_M50k.setText("0");
        txt_nhap.requestFocus();
        txt_nhap.selectAll();
        return;
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CWActionPerformed
        
        if(txt_nhap.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "You not yet fill cash");
            txt_nhap.requestFocus(); 
            return;
        }
        int money = 0;
        try {
            money = Integer.parseInt(txt_nhap.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Login failed");
            txt_nhap.requestFocus();
            txt_nhap.selectAll();
            return;
        }
        
        int m500k, m200k, m100k, m50k;
       m500k = money/500000;
       m200k = (money%500000)/200000;
       m100k = (money%500000%200000)/100000;
       m50k = (money%500000%200000%100000)/50000;
       txt_M500k.setText(Integer.toString(m500k));
       txt_M100k.setText(Integer.toString(m100k));
       txt_M200k.setText(Integer.toString(m200k));
       txt_M50k.setText(Integer.toString(m50k));
       return;
    }//GEN-LAST:event_btn_CWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CW;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_ABC;
    private javax.swing.JLabel lb_M100k;
    private javax.swing.JLabel lb_M200k;
    private javax.swing.JLabel lb_M50k;
    private javax.swing.JLabel lb_M5h;
    private javax.swing.JLabel lb_simple;
    private javax.swing.JTextField txt_M100k;
    private javax.swing.JTextField txt_M200k;
    private javax.swing.JTextField txt_M500k;
    private javax.swing.JTextField txt_M50k;
    private javax.swing.JTextField txt_nhap;
    // End of variables declaration//GEN-END:variables
}
