
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class PTB2 extends javax.swing.JFrame {

    /**
     * Creates new form PTB2
     */
    public PTB2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_pt = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        lb_x2 = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        lb_x = new javax.swing.JLabel();
        txt_c = new javax.swing.JTextField();
        lb_equal = new javax.swing.JLabel();
        lb_nghiem = new javax.swing.JLabel();
        btn_gpt = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giải PT Bậc 2");

        lb_pt.setText("Phương Trình");

        lb_x2.setText("x2");

        lb_x.setText("x+");

        lb_equal.setText("=0");

        lb_nghiem.setText("Nghiệm");

        btn_gpt.setText("Giải PT");
        btn_gpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gptActionPerformed(evt);
            }
        });

        btn_reset.setText("Làm Lại");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        txt_area.setEditable(false);
        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane2.setViewportView(txt_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_pt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_x, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_nghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_gpt)
                                .addGap(32, 32, 32)
                                .addComponent(btn_reset))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pt)
                    .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_x, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_c, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nghiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gpt)
                    .addComponent(btn_reset))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_a.setText("");
        txt_b.setText("");
        txt_c.setText("");
        txt_area.setText("");
        txt_a.requestFocus();
        txt_a.selectAll();
        return;
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_gptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gptActionPerformed
        if(txt_a.getText().equals("") && txt_b.getText().equals("") && txt_c.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "You not yet fill all columns");
            txt_a.requestFocus();
            return;
        }
        
        else 
        {
            if(txt_a.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "You not yet fill in column 1");
                txt_a.requestFocus();
                return;
            }
            double a = 0;
            try {
                    a = Double.parseDouble(txt_a.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed in column 1!!");
                txt_a.requestFocus();
                return;
        }
            if(txt_b.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Yon not yet fill in column 2");
                txt_b.requestFocus();
                return;
            }
            double b =0;
            try {
                b = Double.parseDouble(txt_b.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed in column 2");
                txt_b.requestFocus();
                return;
            }
            
            if(txt_c.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "You not yet fill in column 3");
                txt_c.requestFocus();
                return;
            }
            double c = 0;
            try {
                c = Double.parseDouble(txt_c.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed in column 3");
                txt_c.requestFocus();
                return;
            }
            //Phsn giai phuong trinh bac 2
            float x,y,z;
            x = Float.parseFloat(txt_a.getText());
            y = Float.parseFloat(txt_b.getText());
            z = Float.parseFloat(txt_c.getText());
            if (x == 0)
            {
                if(y == 0)
                {
                    if(z == 0)
                        txt_area.setText("Phuong trinh vo so nghiem");
                    else
                        txt_area.setText("Phuong trinh vo nghiem");
                }
                else txt_area.setText("Phuong trinh co nghiem kep:"+(-z/y));
            }
            else
            {
            float Delta = y*y - 4*x*z;
            float x1,x2,nghiemkep;
            if (Delta > 0)
            {
                x1 = (float)((-y + Math.sqrt(Delta)/(2*x))); 
                x2 = (float)((-y - Math.sqrt(Delta)/(2*x))); 
                txt_area.setText("Phuong trinh co nghiem x1: " +x1+"va x2: " +x2);
                
            }
            if(Delta == 0)
            {
               nghiemkep = (-y)/(2*x);
               txt_area.setText("Phuong trinh co nghiem kep x1,x2: " + nghiemkep);
            }
            else
            {
                txt_area.setText("Phuong trinh vo nghiem");
            }
            
            }
        
        }
       
    }//GEN-LAST:event_btn_gptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PTB2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PTB2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gpt;
    private javax.swing.JButton btn_reset;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_equal;
    private javax.swing.JLabel lb_nghiem;
    private javax.swing.JLabel lb_pt;
    private javax.swing.JLabel lb_x;
    private javax.swing.JLabel lb_x2;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_c;
    // End of variables declaration//GEN-END:variables
}
