
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class XepLoaiHocSinh extends javax.swing.JFrame {

    /**
     * Creates new form ScoreOfStudents
     */
    public XepLoaiHocSinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_hk1 = new javax.swing.JLabel();
        lb_hk2 = new javax.swing.JLabel();
        lb_dtb = new javax.swing.JLabel();
        lb_xl = new javax.swing.JLabel();
        txt_hk1 = new javax.swing.JTextField();
        txt_hk2 = new javax.swing.JTextField();
        txt_dtb = new javax.swing.JTextField();
        txt_xl = new javax.swing.JTextField();
        btn_ok = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Result Of Student");

        lb_hk1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_hk1.setText("Điểm HK1");

        lb_hk2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_hk2.setText("Điểm HK2");

        lb_dtb.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_dtb.setText("Điểm TB");

        lb_xl.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lb_xl.setText("Xếp Loại");

        txt_hk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hk1ActionPerformed(evt);
            }
        });

        txt_hk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hk2ActionPerformed(evt);
            }
        });

        txt_dtb.setEditable(false);
        txt_dtb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dtbActionPerformed(evt);
            }
        });

        txt_xl.setEditable(false);
        txt_xl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_xlActionPerformed(evt);
            }
        });

        btn_ok.setBackground(new java.awt.Color(255, 255, 255));
        btn_ok.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_ok.setForeground(new java.awt.Color(51, 51, 255));
        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(51, 51, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_dtb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_hk1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_hk2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_xl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_hk1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hk2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dtb, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_xl, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_hk1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(lb_hk1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_hk2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hk2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dtb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dtb, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_xl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_xl, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hk1ActionPerformed

    private void txt_hk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hk2ActionPerformed

    private void txt_dtbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dtbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dtbActionPerformed

    private void txt_xlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_xlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_xlActionPerformed

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        if(txt_hk1.getText().equals("") && txt_hk2.getText().equals(""))
        {    JOptionPane.showMessageDialog(this, "Bạn chưa điền điểm HK1 và HK2");
        txt_hk1.requestFocus();
        return;
        }
        
        if(txt_hk1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền điểm HK");
            txt_hk1.requestFocus();
            return;
        }
        double n = 0;
         try {
                n = Double.parseDouble(txt_hk1.getText());
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed in column 1 !!");
            txt_hk1.requestFocus();
            txt_hk1.selectAll();
            return;
            }
        if(txt_hk2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Bạn chưa điền điểm HK2");
            txt_hk2.requestFocus();
            return;
        }
        double m = 0;
         try {
               
                m = Double.parseDouble(txt_hk2.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Failed in column 2 !!");
            txt_hk2.requestFocus();
            txt_hk2.selectAll();
            return;
            }
        if(n<=0)
        {
            JOptionPane.showMessageDialog(this, "Score Quarter must be > 0");
            txt_hk1.requestFocus();
            txt_hk1.selectAll();
            return;
        } 
        if(n<0 || n>10)
        {
            JOptionPane.showMessageDialog(this, "Score Quarter 1 between 0 to 10");
            txt_hk1.requestFocus();
            txt_hk1.selectAll();
            return;
        }
        
        if(m<0 || m>10)
        {
            JOptionPane.showMessageDialog(this, "Score Quarter 2 between 0 to 10");
            txt_hk2.requestFocus();
            txt_hk2.selectAll();
            return;
        }
        
        DecimalFormat df = new DecimalFormat("#.##");
        double dtb = (n + m *2)/3;
        txt_dtb.setText(df.format(dtb));
        if (dtb<5)
            txt_xl.setText("Yếu");
        else if(dtb<7)
            txt_xl.setText("trung bình");
        else if(dtb<8)
            txt_xl.setText("Khá");
        else if(dtb<9)
            txt_xl.setText("Giỏi");
        else txt_xl.setText("Xuất sắc");
        
         
            
        //float a = Float.parseFloat((txt_hk1, txt_hk2)/2);
               
        /*
        
        if (R<=0)
        {
            JOptionPane.showMessageDialog(this, "Bán Kính R phải >0", "Thông Báo Lỗi", JOptionPane.ERROR_MESSAGE);
            txt_NhapR.requestFocus();
            return;
        }
        double P = 2*Math.PI*R, S = Math.PI*R*R;
       txt_CV.setText(Double.toString(P));
       txt_DT.setText(Double.toString(S));
        */
            
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
       txt_hk1.setText("");
       txt_hk2.setText("");
       txt_dtb.setText("");
       txt_xl.setText("");
       txt_hk1.requestFocus();
       txt_hk1.selectAll();
       return;
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XepLoaiHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XepLoaiHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XepLoaiHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XepLoaiHocSinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XepLoaiHocSinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel lb_dtb;
    private javax.swing.JLabel lb_hk1;
    private javax.swing.JLabel lb_hk2;
    private javax.swing.JLabel lb_xl;
    private javax.swing.JTextField txt_dtb;
    private javax.swing.JTextField txt_hk1;
    private javax.swing.JTextField txt_hk2;
    private javax.swing.JTextField txt_xl;
    // End of variables declaration//GEN-END:variables
}
